/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { apiMutator } from './apiMutator'
export type PostApiAuthRegisterBodyOne = {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name: string
  email: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  password: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  confirmPassword: string
}

export type PostApiAuthRegister201OneDataUserAvatar = string | null

export type PostApiAuthRegister201OneDataUserCreatedAt = unknown | string | string | number

export type PostApiAuthRegister201OneDataUserUpdatedAt = unknown | string | string | number

export type PostApiAuthRegister201OneDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiAuthRegister201OneDataUserAvatar
  createdAt: PostApiAuthRegister201OneDataUserCreatedAt
  updatedAt: PostApiAuthRegister201OneDataUserUpdatedAt
}

export type PostApiAuthRegister201OneData = {
  user: PostApiAuthRegister201OneDataUser
  token: string
}

export type PostApiAuthRegister201One = {
  success: boolean
  data: PostApiAuthRegister201OneData
}

export type PostApiAuthRegister400OneErrors = { [key: string]: unknown }

export type PostApiAuthRegister400One = {
  success: boolean
  errors: PostApiAuthRegister400OneErrors
}

export type PostApiAuthRegister422OneErrors = { [key: string]: unknown }

export type PostApiAuthRegister422One = {
  success: boolean
  errors: PostApiAuthRegister422OneErrors
}

export type PostApiAuthLoginBodyOne = {
  email: string
  /** @minLength 1 */
  password: string
}

export type PostApiAuthLogin200OneDataUserAvatar = string | null

export type PostApiAuthLogin200OneDataUserCreatedAt = unknown | string | string | number

export type PostApiAuthLogin200OneDataUserUpdatedAt = unknown | string | string | number

export type PostApiAuthLogin200OneDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiAuthLogin200OneDataUserAvatar
  createdAt: PostApiAuthLogin200OneDataUserCreatedAt
  updatedAt: PostApiAuthLogin200OneDataUserUpdatedAt
}

export type PostApiAuthLogin200OneData = {
  user: PostApiAuthLogin200OneDataUser
  token: string
}

export type PostApiAuthLogin200One = {
  success: boolean
  data: PostApiAuthLogin200OneData
}

export type PostApiAuthLogin422OneErrors = { [key: string]: unknown }

export type PostApiAuthLogin422One = {
  success: boolean
  errors: PostApiAuthLogin422OneErrors
}

export type PostApiAuthLogout200One = {
  success: boolean
  message: string
}

export type GetApiAuthMe200OneDataAvatar = string | null

export type GetApiAuthMe200OneDataCreatedAt = unknown | string | string | number

export type GetApiAuthMe200OneDataUpdatedAt = unknown | string | string | number

export type GetApiAuthMe200OneData = {
  id: string
  name: string
  email: string
  avatar: GetApiAuthMe200OneDataAvatar
  createdAt: GetApiAuthMe200OneDataCreatedAt
  updatedAt: GetApiAuthMe200OneDataUpdatedAt
}

export type GetApiAuthMe200One = {
  success: boolean
  data: GetApiAuthMe200OneData
}

export type GetApiAuthMe404OneErrors = { [key: string]: unknown }

export type GetApiAuthMe404One = {
  success: boolean
  errors: GetApiAuthMe404OneErrors
}

export type GetApiUsersParams = {
  page?: string
  limit?: string
}

export type GetApiUsers200OneDataItemAvatar = string | null

export type GetApiUsers200OneDataItemCreatedAt = unknown | string | string | number

export type GetApiUsers200OneDataItemUpdatedAt = unknown | string | string | number

export type GetApiUsers200OneDataItem = {
  id: string
  name: string
  email: string
  avatar: GetApiUsers200OneDataItemAvatar
  createdAt: GetApiUsers200OneDataItemCreatedAt
  updatedAt: GetApiUsers200OneDataItemUpdatedAt
}

export type GetApiUsers200One = {
  success: boolean
  data: GetApiUsers200OneDataItem[]
  total: number
  page: number
  limit: number
  totalPages: number
}

export type GetApiUsersById200OneDataAvatar = string | null

export type GetApiUsersById200OneDataCreatedAt = unknown | string | string | number

export type GetApiUsersById200OneDataUpdatedAt = unknown | string | string | number

export type GetApiUsersById200OneData = {
  id: string
  name: string
  email: string
  avatar: GetApiUsersById200OneDataAvatar
  createdAt: GetApiUsersById200OneDataCreatedAt
  updatedAt: GetApiUsersById200OneDataUpdatedAt
}

export type GetApiUsersById200One = {
  success: boolean
  data: GetApiUsersById200OneData
}

export type GetApiUsersById404OneErrors = { [key: string]: unknown }

export type GetApiUsersById404One = {
  success: boolean
  errors: GetApiUsersById404OneErrors
}

export type GetApiUsersByIdMarkersParams = {
  page?: string
  limit?: string
}

export type GetApiUsersByIdMarkers200OneDataItemDescription = string | null

export type GetApiUsersByIdMarkers200OneDataItemAddress = string | null

export type GetApiUsersByIdMarkers200OneDataItemImageUrl = string | null

export type GetApiUsersByIdMarkers200OneDataItemCreatedAt = unknown | string | string | number

export type GetApiUsersByIdMarkers200OneDataItemUpdatedAt = unknown | string | string | number

export type GetApiUsersByIdMarkers200OneDataItemUserAvatar = string | null

export type GetApiUsersByIdMarkers200OneDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiUsersByIdMarkers200OneDataItemUserAvatar
}

export type GetApiUsersByIdMarkers200OneDataItem = {
  id: string
  title: string
  description: GetApiUsersByIdMarkers200OneDataItemDescription
  latitude: number
  longitude: number
  address: GetApiUsersByIdMarkers200OneDataItemAddress
  imageUrl: GetApiUsersByIdMarkers200OneDataItemImageUrl
  userId: string
  createdAt: GetApiUsersByIdMarkers200OneDataItemCreatedAt
  updatedAt: GetApiUsersByIdMarkers200OneDataItemUpdatedAt
  user: GetApiUsersByIdMarkers200OneDataItemUser
}

export type GetApiUsersByIdMarkers200One = {
  success: boolean
  data: GetApiUsersByIdMarkers200OneDataItem[]
  total: number
  page: number
  limit: number
  totalPages: number
}

export type GetApiUsersByIdMarkers404OneErrors = { [key: string]: unknown }

export type GetApiUsersByIdMarkers404One = {
  success: boolean
  errors: GetApiUsersByIdMarkers404OneErrors
}

export type PutApiUsersProfileBodyOne = {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name?: string
  avatar?: string
}

export type PutApiUsersProfile200OneDataAvatar = string | null

export type PutApiUsersProfile200OneDataCreatedAt = unknown | string | string | number

export type PutApiUsersProfile200OneDataUpdatedAt = unknown | string | string | number

export type PutApiUsersProfile200OneData = {
  id: string
  name: string
  email: string
  avatar: PutApiUsersProfile200OneDataAvatar
  createdAt: PutApiUsersProfile200OneDataCreatedAt
  updatedAt: PutApiUsersProfile200OneDataUpdatedAt
}

export type PutApiUsersProfile200One = {
  success: boolean
  data: PutApiUsersProfile200OneData
}

export type PutApiUsersProfile404OneErrors = { [key: string]: unknown }

export type PutApiUsersProfile404One = {
  success: boolean
  errors: PutApiUsersProfile404OneErrors
}

export type PutApiUsersPasswordBodyOne = {
  /** @minLength 1 */
  currentPassword: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  newPassword: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  confirmPassword: string
}

export type PutApiUsersPassword200One = {
  success: boolean
  message: string
}

export type PutApiUsersPassword400OneErrors = { [key: string]: unknown }

export type PutApiUsersPassword400One = {
  success: boolean
  errors: PutApiUsersPassword400OneErrors
}

export type PutApiUsersPassword404OneErrors = { [key: string]: unknown }

export type PutApiUsersPassword404One = {
  success: boolean
  errors: PutApiUsersPassword404OneErrors
}

export type DeleteApiUsersAccount200One = {
  success: boolean
  message: string
}

export type GetApiMarkers200OneDataItemDescription = string | null

export type GetApiMarkers200OneDataItemAddress = string | null

export type GetApiMarkers200OneDataItemImageUrl = string | null

export type GetApiMarkers200OneDataItemCreatedAt = unknown | string | string | number

export type GetApiMarkers200OneDataItemUpdatedAt = unknown | string | string | number

export type GetApiMarkers200OneDataItemUserAvatar = string | null

export type GetApiMarkers200OneDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkers200OneDataItemUserAvatar
}

export type GetApiMarkers200OneDataItem = {
  id: string
  title: string
  description: GetApiMarkers200OneDataItemDescription
  latitude: number
  longitude: number
  address: GetApiMarkers200OneDataItemAddress
  imageUrl: GetApiMarkers200OneDataItemImageUrl
  userId: string
  createdAt: GetApiMarkers200OneDataItemCreatedAt
  updatedAt: GetApiMarkers200OneDataItemUpdatedAt
  user: GetApiMarkers200OneDataItemUser
}

export type GetApiMarkers200One = {
  success: boolean
  data: GetApiMarkers200OneDataItem[]
}

export type PostApiMarkersBodyOne = {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string
  /** @maxLength 1000 */
  description?: string
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude: number
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude: number
  /** @maxLength 500 */
  address?: string
  imageUrl?: string
}

export type PostApiMarkers201OneDataDescription = string | null

export type PostApiMarkers201OneDataAddress = string | null

export type PostApiMarkers201OneDataImageUrl = string | null

export type PostApiMarkers201OneDataCreatedAt = unknown | string | string | number

export type PostApiMarkers201OneDataUpdatedAt = unknown | string | string | number

export type PostApiMarkers201OneDataUserAvatar = string | null

export type PostApiMarkers201OneDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiMarkers201OneDataUserAvatar
}

export type PostApiMarkers201OneData = {
  id: string
  title: string
  description: PostApiMarkers201OneDataDescription
  latitude: number
  longitude: number
  address: PostApiMarkers201OneDataAddress
  imageUrl: PostApiMarkers201OneDataImageUrl
  userId: string
  createdAt: PostApiMarkers201OneDataCreatedAt
  updatedAt: PostApiMarkers201OneDataUpdatedAt
  user: PostApiMarkers201OneDataUser
}

export type PostApiMarkers201One = {
  success: boolean
  data: PostApiMarkers201OneData
}

export type PostApiMarkers400OneErrors = { [key: string]: unknown }

export type PostApiMarkers400One = {
  success: boolean
  errors: PostApiMarkers400OneErrors
}

export type GetApiMarkersById200OneDataDescription = string | null

export type GetApiMarkersById200OneDataAddress = string | null

export type GetApiMarkersById200OneDataImageUrl = string | null

export type GetApiMarkersById200OneDataCreatedAt = unknown | string | string | number

export type GetApiMarkersById200OneDataUpdatedAt = unknown | string | string | number

export type GetApiMarkersById200OneDataUserAvatar = string | null

export type GetApiMarkersById200OneDataUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkersById200OneDataUserAvatar
}

export type GetApiMarkersById200OneData = {
  id: string
  title: string
  description: GetApiMarkersById200OneDataDescription
  latitude: number
  longitude: number
  address: GetApiMarkersById200OneDataAddress
  imageUrl: GetApiMarkersById200OneDataImageUrl
  userId: string
  createdAt: GetApiMarkersById200OneDataCreatedAt
  updatedAt: GetApiMarkersById200OneDataUpdatedAt
  user: GetApiMarkersById200OneDataUser
}

export type GetApiMarkersById200One = {
  success: boolean
  data: GetApiMarkersById200OneData
}

export type GetApiMarkersById404OneErrors = { [key: string]: unknown }

export type GetApiMarkersById404One = {
  success: boolean
  errors: GetApiMarkersById404OneErrors
}

export type PutApiMarkersByIdBodyOne = {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string
  /** @maxLength 1000 */
  description?: string
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude?: number
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude?: number
  /** @maxLength 500 */
  address?: string
  imageUrl?: string
}

export type PutApiMarkersById200OneDataDescription = string | null

export type PutApiMarkersById200OneDataAddress = string | null

export type PutApiMarkersById200OneDataImageUrl = string | null

export type PutApiMarkersById200OneDataCreatedAt = unknown | string | string | number

export type PutApiMarkersById200OneDataUpdatedAt = unknown | string | string | number

export type PutApiMarkersById200OneDataUserAvatar = string | null

export type PutApiMarkersById200OneDataUser = {
  id: string
  name: string
  email: string
  avatar: PutApiMarkersById200OneDataUserAvatar
}

export type PutApiMarkersById200OneData = {
  id: string
  title: string
  description: PutApiMarkersById200OneDataDescription
  latitude: number
  longitude: number
  address: PutApiMarkersById200OneDataAddress
  imageUrl: PutApiMarkersById200OneDataImageUrl
  userId: string
  createdAt: PutApiMarkersById200OneDataCreatedAt
  updatedAt: PutApiMarkersById200OneDataUpdatedAt
  user: PutApiMarkersById200OneDataUser
}

export type PutApiMarkersById200One = {
  success: boolean
  data: PutApiMarkersById200OneData
}

export type PutApiMarkersById403OneErrors = { [key: string]: unknown }

export type PutApiMarkersById403One = {
  success: boolean
  errors: PutApiMarkersById403OneErrors
}

export type PutApiMarkersById404OneErrors = { [key: string]: unknown }

export type PutApiMarkersById404One = {
  success: boolean
  errors: PutApiMarkersById404OneErrors
}

export type DeleteApiMarkersById200One = {
  success: boolean
  message: string
}

export type DeleteApiMarkersById403OneErrors = { [key: string]: unknown }

export type DeleteApiMarkersById403One = {
  success: boolean
  errors: DeleteApiMarkersById403OneErrors
}

export type DeleteApiMarkersById404OneErrors = { [key: string]: unknown }

export type DeleteApiMarkersById404One = {
  success: boolean
  errors: DeleteApiMarkersById404OneErrors
}

export type GetApiMarkersMyMarkers200OneDataItemDescription = string | null

export type GetApiMarkersMyMarkers200OneDataItemAddress = string | null

export type GetApiMarkersMyMarkers200OneDataItemImageUrl = string | null

export type GetApiMarkersMyMarkers200OneDataItemCreatedAt = unknown | string | string | number

export type GetApiMarkersMyMarkers200OneDataItemUpdatedAt = unknown | string | string | number

export type GetApiMarkersMyMarkers200OneDataItemUserAvatar = string | null

export type GetApiMarkersMyMarkers200OneDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkersMyMarkers200OneDataItemUserAvatar
}

export type GetApiMarkersMyMarkers200OneDataItem = {
  id: string
  title: string
  description: GetApiMarkersMyMarkers200OneDataItemDescription
  latitude: number
  longitude: number
  address: GetApiMarkersMyMarkers200OneDataItemAddress
  imageUrl: GetApiMarkersMyMarkers200OneDataItemImageUrl
  userId: string
  createdAt: GetApiMarkersMyMarkers200OneDataItemCreatedAt
  updatedAt: GetApiMarkersMyMarkers200OneDataItemUpdatedAt
  user: GetApiMarkersMyMarkers200OneDataItemUser
}

export type GetApiMarkersMyMarkers200One = {
  success: boolean
  data: GetApiMarkersMyMarkers200OneDataItem[]
}

export const getElysiaDocumentation = () => {
  const postApiAuthRegister = (postApiAuthRegisterBodyOne: PostApiAuthRegisterBodyOne) => {
    return apiMutator<PostApiAuthRegister201One>({
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiAuthRegisterBodyOne,
    })
  }

  const postApiAuthLogin = (postApiAuthLoginBodyOne: PostApiAuthLoginBodyOne) => {
    return apiMutator<PostApiAuthLogin200One>({
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiAuthLoginBodyOne,
    })
  }

  const postApiAuthLogout = () => {
    return apiMutator<PostApiAuthLogout200One>({ url: `/api/auth/logout`, method: 'POST' })
  }

  const getApiAuthMe = () => {
    return apiMutator<GetApiAuthMe200One>({ url: `/api/auth/me`, method: 'GET' })
  }

  const getApiUsers = (params?: GetApiUsersParams) => {
    return apiMutator<GetApiUsers200One>({ url: `/api/users/`, method: 'GET', params })
  }

  const getApiUsersById = (id: string) => {
    return apiMutator<GetApiUsersById200One>({ url: `/api/users/${id}`, method: 'GET' })
  }

  const getApiUsersByIdMarkers = (id: string, params?: GetApiUsersByIdMarkersParams) => {
    return apiMutator<GetApiUsersByIdMarkers200One>({
      url: `/api/users/${id}/markers`,
      method: 'GET',
      params,
    })
  }

  const putApiUsersProfile = (putApiUsersProfileBodyOne: PutApiUsersProfileBodyOne) => {
    return apiMutator<PutApiUsersProfile200One>({
      url: `/api/users/profile`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: putApiUsersProfileBodyOne,
    })
  }

  const putApiUsersPassword = (putApiUsersPasswordBodyOne: PutApiUsersPasswordBodyOne) => {
    return apiMutator<PutApiUsersPassword200One>({
      url: `/api/users/password`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: putApiUsersPasswordBodyOne,
    })
  }

  const deleteApiUsersAccount = () => {
    return apiMutator<DeleteApiUsersAccount200One>({ url: `/api/users/account`, method: 'DELETE' })
  }

  const getApiMarkers = () => {
    return apiMutator<GetApiMarkers200One>({ url: `/api/markers/`, method: 'GET' })
  }

  const postApiMarkers = (postApiMarkersBodyOne: PostApiMarkersBodyOne) => {
    return apiMutator<PostApiMarkers201One>({
      url: `/api/markers/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiMarkersBodyOne,
    })
  }

  const getApiMarkersById = (id: string) => {
    return apiMutator<GetApiMarkersById200One>({ url: `/api/markers/${id}`, method: 'GET' })
  }

  const putApiMarkersById = (id: string, putApiMarkersByIdBodyOne: PutApiMarkersByIdBodyOne) => {
    return apiMutator<PutApiMarkersById200One>({
      url: `/api/markers/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: putApiMarkersByIdBodyOne,
    })
  }

  const deleteApiMarkersById = (id: string) => {
    return apiMutator<DeleteApiMarkersById200One>({ url: `/api/markers/${id}`, method: 'DELETE' })
  }

  const getApiMarkersMyMarkers = () => {
    return apiMutator<GetApiMarkersMyMarkers200One>({
      url: `/api/markers/my/markers`,
      method: 'GET',
    })
  }

  return {
    postApiAuthRegister,
    postApiAuthLogin,
    postApiAuthLogout,
    getApiAuthMe,
    getApiUsers,
    getApiUsersById,
    getApiUsersByIdMarkers,
    putApiUsersProfile,
    putApiUsersPassword,
    deleteApiUsersAccount,
    getApiMarkers,
    postApiMarkers,
    getApiMarkersById,
    putApiMarkersById,
    deleteApiMarkersById,
    getApiMarkersMyMarkers,
  }
}
export type PostApiAuthRegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['postApiAuthRegister']>>
>
export type PostApiAuthLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['postApiAuthLogin']>>
>
export type PostApiAuthLogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['postApiAuthLogout']>>
>
export type GetApiAuthMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiAuthMe']>>
>
export type GetApiUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiUsers']>>
>
export type GetApiUsersByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiUsersById']>>
>
export type GetApiUsersByIdMarkersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiUsersByIdMarkers']>>
>
export type PutApiUsersProfileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['putApiUsersProfile']>>
>
export type PutApiUsersPasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['putApiUsersPassword']>>
>
export type DeleteApiUsersAccountResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['deleteApiUsersAccount']>>
>
export type GetApiMarkersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiMarkers']>>
>
export type PostApiMarkersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['postApiMarkers']>>
>
export type GetApiMarkersByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiMarkersById']>>
>
export type PutApiMarkersByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['putApiMarkersById']>>
>
export type DeleteApiMarkersByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['deleteApiMarkersById']>>
>
export type GetApiMarkersMyMarkersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiMarkersMyMarkers']>>
>
