/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { apiMutator } from './apiMutator'
export type PostApiAuthRegisterBodyOne = {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name: string
  email: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  password: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  confirmPassword: string
}

export type PostApiAuthRegisterBodyTwo = {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name: string
  email: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  password: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  confirmPassword: string
}

export type PostApiAuthRegisterBodyThree = {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name: string
  email: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  password: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  confirmPassword: string
}

export type PostApiAuthRegister201OneDataUserAvatar = string | null

export type PostApiAuthRegister201OneDataUserCreatedAt = unknown | string | string | number

export type PostApiAuthRegister201OneDataUserUpdatedAt = unknown | string | string | number

export type PostApiAuthRegister201OneDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiAuthRegister201OneDataUserAvatar
  createdAt: PostApiAuthRegister201OneDataUserCreatedAt
  updatedAt: PostApiAuthRegister201OneDataUserUpdatedAt
}

export type PostApiAuthRegister201OneData = {
  user: PostApiAuthRegister201OneDataUser
  token: string
}

export type PostApiAuthRegister201One = {
  success: boolean
  data: PostApiAuthRegister201OneData
}

export type PostApiAuthRegister201TwoDataUserAvatar = string | null

export type PostApiAuthRegister201TwoDataUserCreatedAt = unknown | string | string | number

export type PostApiAuthRegister201TwoDataUserUpdatedAt = unknown | string | string | number

export type PostApiAuthRegister201TwoDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiAuthRegister201TwoDataUserAvatar
  createdAt: PostApiAuthRegister201TwoDataUserCreatedAt
  updatedAt: PostApiAuthRegister201TwoDataUserUpdatedAt
}

export type PostApiAuthRegister201TwoData = {
  user: PostApiAuthRegister201TwoDataUser
  token: string
}

export type PostApiAuthRegister201Two = {
  success: boolean
  data: PostApiAuthRegister201TwoData
}

export type PostApiAuthRegister201ThreeDataUserAvatar = string | null

export type PostApiAuthRegister201ThreeDataUserCreatedAt = unknown | string | string | number

export type PostApiAuthRegister201ThreeDataUserUpdatedAt = unknown | string | string | number

export type PostApiAuthRegister201ThreeDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiAuthRegister201ThreeDataUserAvatar
  createdAt: PostApiAuthRegister201ThreeDataUserCreatedAt
  updatedAt: PostApiAuthRegister201ThreeDataUserUpdatedAt
}

export type PostApiAuthRegister201ThreeData = {
  user: PostApiAuthRegister201ThreeDataUser
  token: string
}

export type PostApiAuthRegister201Three = {
  success: boolean
  data: PostApiAuthRegister201ThreeData
}

export type PostApiAuthRegister400One = {
  success: boolean
  message: string
}

export type PostApiAuthRegister400Two = {
  success: boolean
  message: string
}

export type PostApiAuthRegister400Three = {
  success: boolean
  message: string
}

export type PostApiAuthLoginBodyOne = {
  email: string
  /** @minLength 1 */
  password: string
}

export type PostApiAuthLoginBodyTwo = {
  email: string
  /** @minLength 1 */
  password: string
}

export type PostApiAuthLoginBodyThree = {
  email: string
  /** @minLength 1 */
  password: string
}

export type PostApiAuthLogin200OneDataUserAvatar = string | null

export type PostApiAuthLogin200OneDataUserCreatedAt = unknown | string | string | number

export type PostApiAuthLogin200OneDataUserUpdatedAt = unknown | string | string | number

export type PostApiAuthLogin200OneDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiAuthLogin200OneDataUserAvatar
  createdAt: PostApiAuthLogin200OneDataUserCreatedAt
  updatedAt: PostApiAuthLogin200OneDataUserUpdatedAt
}

export type PostApiAuthLogin200OneData = {
  user: PostApiAuthLogin200OneDataUser
  token: string
}

export type PostApiAuthLogin200One = {
  success: boolean
  data: PostApiAuthLogin200OneData
}

export type PostApiAuthLogin200TwoDataUserAvatar = string | null

export type PostApiAuthLogin200TwoDataUserCreatedAt = unknown | string | string | number

export type PostApiAuthLogin200TwoDataUserUpdatedAt = unknown | string | string | number

export type PostApiAuthLogin200TwoDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiAuthLogin200TwoDataUserAvatar
  createdAt: PostApiAuthLogin200TwoDataUserCreatedAt
  updatedAt: PostApiAuthLogin200TwoDataUserUpdatedAt
}

export type PostApiAuthLogin200TwoData = {
  user: PostApiAuthLogin200TwoDataUser
  token: string
}

export type PostApiAuthLogin200Two = {
  success: boolean
  data: PostApiAuthLogin200TwoData
}

export type PostApiAuthLogin200ThreeDataUserAvatar = string | null

export type PostApiAuthLogin200ThreeDataUserCreatedAt = unknown | string | string | number

export type PostApiAuthLogin200ThreeDataUserUpdatedAt = unknown | string | string | number

export type PostApiAuthLogin200ThreeDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiAuthLogin200ThreeDataUserAvatar
  createdAt: PostApiAuthLogin200ThreeDataUserCreatedAt
  updatedAt: PostApiAuthLogin200ThreeDataUserUpdatedAt
}

export type PostApiAuthLogin200ThreeData = {
  user: PostApiAuthLogin200ThreeDataUser
  token: string
}

export type PostApiAuthLogin200Three = {
  success: boolean
  data: PostApiAuthLogin200ThreeData
}

export type PostApiAuthLogin401One = {
  success: boolean
  message: string
}

export type PostApiAuthLogin401Two = {
  success: boolean
  message: string
}

export type PostApiAuthLogin401Three = {
  success: boolean
  message: string
}

export type PostApiAuthLogout200One = {
  success: boolean
  message: string
}

export type PostApiAuthLogout200Two = {
  success: boolean
  message: string
}

export type PostApiAuthLogout200Three = {
  success: boolean
  message: string
}

export type GetApiAuthMe200OneDataAvatar = string | null

export type GetApiAuthMe200OneDataCreatedAt = unknown | string | string | number

export type GetApiAuthMe200OneDataUpdatedAt = unknown | string | string | number

export type GetApiAuthMe200OneData = {
  id: string
  name: string
  email: string
  avatar: GetApiAuthMe200OneDataAvatar
  createdAt: GetApiAuthMe200OneDataCreatedAt
  updatedAt: GetApiAuthMe200OneDataUpdatedAt
}

export type GetApiAuthMe200One = {
  success: boolean
  data: GetApiAuthMe200OneData
}

export type GetApiAuthMe200TwoDataAvatar = string | null

export type GetApiAuthMe200TwoDataCreatedAt = unknown | string | string | number

export type GetApiAuthMe200TwoDataUpdatedAt = unknown | string | string | number

export type GetApiAuthMe200TwoData = {
  id: string
  name: string
  email: string
  avatar: GetApiAuthMe200TwoDataAvatar
  createdAt: GetApiAuthMe200TwoDataCreatedAt
  updatedAt: GetApiAuthMe200TwoDataUpdatedAt
}

export type GetApiAuthMe200Two = {
  success: boolean
  data: GetApiAuthMe200TwoData
}

export type GetApiAuthMe200ThreeDataAvatar = string | null

export type GetApiAuthMe200ThreeDataCreatedAt = unknown | string | string | number

export type GetApiAuthMe200ThreeDataUpdatedAt = unknown | string | string | number

export type GetApiAuthMe200ThreeData = {
  id: string
  name: string
  email: string
  avatar: GetApiAuthMe200ThreeDataAvatar
  createdAt: GetApiAuthMe200ThreeDataCreatedAt
  updatedAt: GetApiAuthMe200ThreeDataUpdatedAt
}

export type GetApiAuthMe200Three = {
  success: boolean
  data: GetApiAuthMe200ThreeData
}

export type GetApiAuthMe404One = {
  success: boolean
  message: string
}

export type GetApiAuthMe404Two = {
  success: boolean
  message: string
}

export type GetApiAuthMe404Three = {
  success: boolean
  message: string
}

export type GetApiUsersParams = {
  page?: string
  limit?: string
}

export type GetApiUsers200OneDataItemAvatar = string | null

export type GetApiUsers200OneDataItemCreatedAt = unknown | string | string | number

export type GetApiUsers200OneDataItemUpdatedAt = unknown | string | string | number

export type GetApiUsers200OneDataItem = {
  id: string
  name: string
  email: string
  avatar: GetApiUsers200OneDataItemAvatar
  createdAt: GetApiUsers200OneDataItemCreatedAt
  updatedAt: GetApiUsers200OneDataItemUpdatedAt
}

export type GetApiUsers200One = {
  success: boolean
  data: GetApiUsers200OneDataItem[]
  total: number
  page: number
  limit: number
  totalPages: number
}

export type GetApiUsers200TwoDataItemAvatar = string | null

export type GetApiUsers200TwoDataItemCreatedAt = unknown | string | string | number

export type GetApiUsers200TwoDataItemUpdatedAt = unknown | string | string | number

export type GetApiUsers200TwoDataItem = {
  id: string
  name: string
  email: string
  avatar: GetApiUsers200TwoDataItemAvatar
  createdAt: GetApiUsers200TwoDataItemCreatedAt
  updatedAt: GetApiUsers200TwoDataItemUpdatedAt
}

export type GetApiUsers200Two = {
  success: boolean
  data: GetApiUsers200TwoDataItem[]
  total: number
  page: number
  limit: number
  totalPages: number
}

export type GetApiUsers200ThreeDataItemAvatar = string | null

export type GetApiUsers200ThreeDataItemCreatedAt = unknown | string | string | number

export type GetApiUsers200ThreeDataItemUpdatedAt = unknown | string | string | number

export type GetApiUsers200ThreeDataItem = {
  id: string
  name: string
  email: string
  avatar: GetApiUsers200ThreeDataItemAvatar
  createdAt: GetApiUsers200ThreeDataItemCreatedAt
  updatedAt: GetApiUsers200ThreeDataItemUpdatedAt
}

export type GetApiUsers200Three = {
  success: boolean
  data: GetApiUsers200ThreeDataItem[]
  total: number
  page: number
  limit: number
  totalPages: number
}

export type GetApiUsersById200OneDataAvatar = string | null

export type GetApiUsersById200OneDataCreatedAt = unknown | string | string | number

export type GetApiUsersById200OneDataUpdatedAt = unknown | string | string | number

export type GetApiUsersById200OneData = {
  id: string
  name: string
  email: string
  avatar: GetApiUsersById200OneDataAvatar
  createdAt: GetApiUsersById200OneDataCreatedAt
  updatedAt: GetApiUsersById200OneDataUpdatedAt
}

export type GetApiUsersById200One = {
  success: boolean
  data: GetApiUsersById200OneData
}

export type GetApiUsersById200TwoDataAvatar = string | null

export type GetApiUsersById200TwoDataCreatedAt = unknown | string | string | number

export type GetApiUsersById200TwoDataUpdatedAt = unknown | string | string | number

export type GetApiUsersById200TwoData = {
  id: string
  name: string
  email: string
  avatar: GetApiUsersById200TwoDataAvatar
  createdAt: GetApiUsersById200TwoDataCreatedAt
  updatedAt: GetApiUsersById200TwoDataUpdatedAt
}

export type GetApiUsersById200Two = {
  success: boolean
  data: GetApiUsersById200TwoData
}

export type GetApiUsersById200ThreeDataAvatar = string | null

export type GetApiUsersById200ThreeDataCreatedAt = unknown | string | string | number

export type GetApiUsersById200ThreeDataUpdatedAt = unknown | string | string | number

export type GetApiUsersById200ThreeData = {
  id: string
  name: string
  email: string
  avatar: GetApiUsersById200ThreeDataAvatar
  createdAt: GetApiUsersById200ThreeDataCreatedAt
  updatedAt: GetApiUsersById200ThreeDataUpdatedAt
}

export type GetApiUsersById200Three = {
  success: boolean
  data: GetApiUsersById200ThreeData
}

export type GetApiUsersById404One = {
  success: boolean
  message: string
}

export type GetApiUsersById404Two = {
  success: boolean
  message: string
}

export type GetApiUsersById404Three = {
  success: boolean
  message: string
}

export type GetApiUsersByIdMarkersParams = {
  page?: string
  limit?: string
}

export type GetApiUsersByIdMarkers200OneDataItemDescription = string | null

export type GetApiUsersByIdMarkers200OneDataItemAddress = string | null

export type GetApiUsersByIdMarkers200OneDataItemImageUrl = string | null

export type GetApiUsersByIdMarkers200OneDataItemCreatedAt = unknown | string | string | number

export type GetApiUsersByIdMarkers200OneDataItemUpdatedAt = unknown | string | string | number

export type GetApiUsersByIdMarkers200OneDataItemUserAvatar = string | null

export type GetApiUsersByIdMarkers200OneDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiUsersByIdMarkers200OneDataItemUserAvatar
}

export type GetApiUsersByIdMarkers200OneDataItem = {
  id: string
  title: string
  description: GetApiUsersByIdMarkers200OneDataItemDescription
  latitude: number
  longitude: number
  address: GetApiUsersByIdMarkers200OneDataItemAddress
  imageUrl: GetApiUsersByIdMarkers200OneDataItemImageUrl
  userId: string
  createdAt: GetApiUsersByIdMarkers200OneDataItemCreatedAt
  updatedAt: GetApiUsersByIdMarkers200OneDataItemUpdatedAt
  user: GetApiUsersByIdMarkers200OneDataItemUser
}

export type GetApiUsersByIdMarkers200One = {
  success: boolean
  data: GetApiUsersByIdMarkers200OneDataItem[]
  total: number
  page: number
  limit: number
  totalPages: number
}

export type GetApiUsersByIdMarkers200TwoDataItemDescription = string | null

export type GetApiUsersByIdMarkers200TwoDataItemAddress = string | null

export type GetApiUsersByIdMarkers200TwoDataItemImageUrl = string | null

export type GetApiUsersByIdMarkers200TwoDataItemCreatedAt = unknown | string | string | number

export type GetApiUsersByIdMarkers200TwoDataItemUpdatedAt = unknown | string | string | number

export type GetApiUsersByIdMarkers200TwoDataItemUserAvatar = string | null

export type GetApiUsersByIdMarkers200TwoDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiUsersByIdMarkers200TwoDataItemUserAvatar
}

export type GetApiUsersByIdMarkers200TwoDataItem = {
  id: string
  title: string
  description: GetApiUsersByIdMarkers200TwoDataItemDescription
  latitude: number
  longitude: number
  address: GetApiUsersByIdMarkers200TwoDataItemAddress
  imageUrl: GetApiUsersByIdMarkers200TwoDataItemImageUrl
  userId: string
  createdAt: GetApiUsersByIdMarkers200TwoDataItemCreatedAt
  updatedAt: GetApiUsersByIdMarkers200TwoDataItemUpdatedAt
  user: GetApiUsersByIdMarkers200TwoDataItemUser
}

export type GetApiUsersByIdMarkers200Two = {
  success: boolean
  data: GetApiUsersByIdMarkers200TwoDataItem[]
  total: number
  page: number
  limit: number
  totalPages: number
}

export type GetApiUsersByIdMarkers200ThreeDataItemDescription = string | null

export type GetApiUsersByIdMarkers200ThreeDataItemAddress = string | null

export type GetApiUsersByIdMarkers200ThreeDataItemImageUrl = string | null

export type GetApiUsersByIdMarkers200ThreeDataItemCreatedAt = unknown | string | string | number

export type GetApiUsersByIdMarkers200ThreeDataItemUpdatedAt = unknown | string | string | number

export type GetApiUsersByIdMarkers200ThreeDataItemUserAvatar = string | null

export type GetApiUsersByIdMarkers200ThreeDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiUsersByIdMarkers200ThreeDataItemUserAvatar
}

export type GetApiUsersByIdMarkers200ThreeDataItem = {
  id: string
  title: string
  description: GetApiUsersByIdMarkers200ThreeDataItemDescription
  latitude: number
  longitude: number
  address: GetApiUsersByIdMarkers200ThreeDataItemAddress
  imageUrl: GetApiUsersByIdMarkers200ThreeDataItemImageUrl
  userId: string
  createdAt: GetApiUsersByIdMarkers200ThreeDataItemCreatedAt
  updatedAt: GetApiUsersByIdMarkers200ThreeDataItemUpdatedAt
  user: GetApiUsersByIdMarkers200ThreeDataItemUser
}

export type GetApiUsersByIdMarkers200Three = {
  success: boolean
  data: GetApiUsersByIdMarkers200ThreeDataItem[]
  total: number
  page: number
  limit: number
  totalPages: number
}

export type GetApiUsersByIdMarkers404One = {
  success: boolean
  message: string
}

export type GetApiUsersByIdMarkers404Two = {
  success: boolean
  message: string
}

export type GetApiUsersByIdMarkers404Three = {
  success: boolean
  message: string
}

export type PutApiUsersProfileBodyOne = {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name?: string
  avatar?: string
}

export type PutApiUsersProfileBodyTwo = {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name?: string
  avatar?: string
}

export type PutApiUsersProfileBodyThree = {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name?: string
  avatar?: string
}

export type PutApiUsersProfile200OneDataAvatar = string | null

export type PutApiUsersProfile200OneDataCreatedAt = unknown | string | string | number

export type PutApiUsersProfile200OneDataUpdatedAt = unknown | string | string | number

export type PutApiUsersProfile200OneData = {
  id: string
  name: string
  email: string
  avatar: PutApiUsersProfile200OneDataAvatar
  createdAt: PutApiUsersProfile200OneDataCreatedAt
  updatedAt: PutApiUsersProfile200OneDataUpdatedAt
}

export type PutApiUsersProfile200One = {
  success: boolean
  data: PutApiUsersProfile200OneData
}

export type PutApiUsersProfile200TwoDataAvatar = string | null

export type PutApiUsersProfile200TwoDataCreatedAt = unknown | string | string | number

export type PutApiUsersProfile200TwoDataUpdatedAt = unknown | string | string | number

export type PutApiUsersProfile200TwoData = {
  id: string
  name: string
  email: string
  avatar: PutApiUsersProfile200TwoDataAvatar
  createdAt: PutApiUsersProfile200TwoDataCreatedAt
  updatedAt: PutApiUsersProfile200TwoDataUpdatedAt
}

export type PutApiUsersProfile200Two = {
  success: boolean
  data: PutApiUsersProfile200TwoData
}

export type PutApiUsersProfile200ThreeDataAvatar = string | null

export type PutApiUsersProfile200ThreeDataCreatedAt = unknown | string | string | number

export type PutApiUsersProfile200ThreeDataUpdatedAt = unknown | string | string | number

export type PutApiUsersProfile200ThreeData = {
  id: string
  name: string
  email: string
  avatar: PutApiUsersProfile200ThreeDataAvatar
  createdAt: PutApiUsersProfile200ThreeDataCreatedAt
  updatedAt: PutApiUsersProfile200ThreeDataUpdatedAt
}

export type PutApiUsersProfile200Three = {
  success: boolean
  data: PutApiUsersProfile200ThreeData
}

export type PutApiUsersProfile404One = {
  success: boolean
  message: string
}

export type PutApiUsersProfile404Two = {
  success: boolean
  message: string
}

export type PutApiUsersProfile404Three = {
  success: boolean
  message: string
}

export type PutApiUsersPasswordBodyOne = {
  /** @minLength 1 */
  currentPassword: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  newPassword: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  confirmPassword: string
}

export type PutApiUsersPasswordBodyTwo = {
  /** @minLength 1 */
  currentPassword: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  newPassword: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  confirmPassword: string
}

export type PutApiUsersPasswordBodyThree = {
  /** @minLength 1 */
  currentPassword: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  newPassword: string
  /**
   * @minLength 6
   * @maxLength 100
   */
  confirmPassword: string
}

export type PutApiUsersPassword200One = {
  success: boolean
  message: string
}

export type PutApiUsersPassword200Two = {
  success: boolean
  message: string
}

export type PutApiUsersPassword200Three = {
  success: boolean
  message: string
}

export type PutApiUsersPassword400One = {
  success: boolean
  message: string
}

export type PutApiUsersPassword400Two = {
  success: boolean
  message: string
}

export type PutApiUsersPassword400Three = {
  success: boolean
  message: string
}

export type PutApiUsersPassword404One = {
  success: boolean
  message: string
}

export type PutApiUsersPassword404Two = {
  success: boolean
  message: string
}

export type PutApiUsersPassword404Three = {
  success: boolean
  message: string
}

export type DeleteApiUsersAccount200One = {
  success: boolean
  message: string
}

export type DeleteApiUsersAccount200Two = {
  success: boolean
  message: string
}

export type DeleteApiUsersAccount200Three = {
  success: boolean
  message: string
}

export type GetApiMarkers200OneDataItemDescription = string | null

export type GetApiMarkers200OneDataItemAddress = string | null

export type GetApiMarkers200OneDataItemImageUrl = string | null

export type GetApiMarkers200OneDataItemCreatedAt = unknown | string | string | number

export type GetApiMarkers200OneDataItemUpdatedAt = unknown | string | string | number

export type GetApiMarkers200OneDataItemUserAvatar = string | null

export type GetApiMarkers200OneDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkers200OneDataItemUserAvatar
}

export type GetApiMarkers200OneDataItem = {
  id: string
  title: string
  description: GetApiMarkers200OneDataItemDescription
  latitude: number
  longitude: number
  address: GetApiMarkers200OneDataItemAddress
  imageUrl: GetApiMarkers200OneDataItemImageUrl
  userId: string
  createdAt: GetApiMarkers200OneDataItemCreatedAt
  updatedAt: GetApiMarkers200OneDataItemUpdatedAt
  user: GetApiMarkers200OneDataItemUser
}

export type GetApiMarkers200One = {
  success: boolean
  data: GetApiMarkers200OneDataItem[]
}

export type GetApiMarkers200TwoDataItemDescription = string | null

export type GetApiMarkers200TwoDataItemAddress = string | null

export type GetApiMarkers200TwoDataItemImageUrl = string | null

export type GetApiMarkers200TwoDataItemCreatedAt = unknown | string | string | number

export type GetApiMarkers200TwoDataItemUpdatedAt = unknown | string | string | number

export type GetApiMarkers200TwoDataItemUserAvatar = string | null

export type GetApiMarkers200TwoDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkers200TwoDataItemUserAvatar
}

export type GetApiMarkers200TwoDataItem = {
  id: string
  title: string
  description: GetApiMarkers200TwoDataItemDescription
  latitude: number
  longitude: number
  address: GetApiMarkers200TwoDataItemAddress
  imageUrl: GetApiMarkers200TwoDataItemImageUrl
  userId: string
  createdAt: GetApiMarkers200TwoDataItemCreatedAt
  updatedAt: GetApiMarkers200TwoDataItemUpdatedAt
  user: GetApiMarkers200TwoDataItemUser
}

export type GetApiMarkers200Two = {
  success: boolean
  data: GetApiMarkers200TwoDataItem[]
}

export type GetApiMarkers200ThreeDataItemDescription = string | null

export type GetApiMarkers200ThreeDataItemAddress = string | null

export type GetApiMarkers200ThreeDataItemImageUrl = string | null

export type GetApiMarkers200ThreeDataItemCreatedAt = unknown | string | string | number

export type GetApiMarkers200ThreeDataItemUpdatedAt = unknown | string | string | number

export type GetApiMarkers200ThreeDataItemUserAvatar = string | null

export type GetApiMarkers200ThreeDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkers200ThreeDataItemUserAvatar
}

export type GetApiMarkers200ThreeDataItem = {
  id: string
  title: string
  description: GetApiMarkers200ThreeDataItemDescription
  latitude: number
  longitude: number
  address: GetApiMarkers200ThreeDataItemAddress
  imageUrl: GetApiMarkers200ThreeDataItemImageUrl
  userId: string
  createdAt: GetApiMarkers200ThreeDataItemCreatedAt
  updatedAt: GetApiMarkers200ThreeDataItemUpdatedAt
  user: GetApiMarkers200ThreeDataItemUser
}

export type GetApiMarkers200Three = {
  success: boolean
  data: GetApiMarkers200ThreeDataItem[]
}

export type PostApiMarkersBodyOne = {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string
  /** @maxLength 1000 */
  description?: string
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude: number
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude: number
  /** @maxLength 500 */
  address?: string
  imageUrl?: string
}

export type PostApiMarkersBodyTwo = {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string
  /** @maxLength 1000 */
  description?: string
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude: number
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude: number
  /** @maxLength 500 */
  address?: string
  imageUrl?: string
}

export type PostApiMarkersBodyThree = {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string
  /** @maxLength 1000 */
  description?: string
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude: number
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude: number
  /** @maxLength 500 */
  address?: string
  imageUrl?: string
}

export type PostApiMarkers201OneDataDescription = string | null

export type PostApiMarkers201OneDataAddress = string | null

export type PostApiMarkers201OneDataImageUrl = string | null

export type PostApiMarkers201OneDataCreatedAt = unknown | string | string | number

export type PostApiMarkers201OneDataUpdatedAt = unknown | string | string | number

export type PostApiMarkers201OneDataUserAvatar = string | null

export type PostApiMarkers201OneDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiMarkers201OneDataUserAvatar
}

export type PostApiMarkers201OneData = {
  id: string
  title: string
  description: PostApiMarkers201OneDataDescription
  latitude: number
  longitude: number
  address: PostApiMarkers201OneDataAddress
  imageUrl: PostApiMarkers201OneDataImageUrl
  userId: string
  createdAt: PostApiMarkers201OneDataCreatedAt
  updatedAt: PostApiMarkers201OneDataUpdatedAt
  user: PostApiMarkers201OneDataUser
}

export type PostApiMarkers201One = {
  success: boolean
  data: PostApiMarkers201OneData
}

export type PostApiMarkers201TwoDataDescription = string | null

export type PostApiMarkers201TwoDataAddress = string | null

export type PostApiMarkers201TwoDataImageUrl = string | null

export type PostApiMarkers201TwoDataCreatedAt = unknown | string | string | number

export type PostApiMarkers201TwoDataUpdatedAt = unknown | string | string | number

export type PostApiMarkers201TwoDataUserAvatar = string | null

export type PostApiMarkers201TwoDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiMarkers201TwoDataUserAvatar
}

export type PostApiMarkers201TwoData = {
  id: string
  title: string
  description: PostApiMarkers201TwoDataDescription
  latitude: number
  longitude: number
  address: PostApiMarkers201TwoDataAddress
  imageUrl: PostApiMarkers201TwoDataImageUrl
  userId: string
  createdAt: PostApiMarkers201TwoDataCreatedAt
  updatedAt: PostApiMarkers201TwoDataUpdatedAt
  user: PostApiMarkers201TwoDataUser
}

export type PostApiMarkers201Two = {
  success: boolean
  data: PostApiMarkers201TwoData
}

export type PostApiMarkers201ThreeDataDescription = string | null

export type PostApiMarkers201ThreeDataAddress = string | null

export type PostApiMarkers201ThreeDataImageUrl = string | null

export type PostApiMarkers201ThreeDataCreatedAt = unknown | string | string | number

export type PostApiMarkers201ThreeDataUpdatedAt = unknown | string | string | number

export type PostApiMarkers201ThreeDataUserAvatar = string | null

export type PostApiMarkers201ThreeDataUser = {
  id: string
  name: string
  email: string
  avatar: PostApiMarkers201ThreeDataUserAvatar
}

export type PostApiMarkers201ThreeData = {
  id: string
  title: string
  description: PostApiMarkers201ThreeDataDescription
  latitude: number
  longitude: number
  address: PostApiMarkers201ThreeDataAddress
  imageUrl: PostApiMarkers201ThreeDataImageUrl
  userId: string
  createdAt: PostApiMarkers201ThreeDataCreatedAt
  updatedAt: PostApiMarkers201ThreeDataUpdatedAt
  user: PostApiMarkers201ThreeDataUser
}

export type PostApiMarkers201Three = {
  success: boolean
  data: PostApiMarkers201ThreeData
}

export type PostApiMarkers400One = {
  success: boolean
  message: string
}

export type PostApiMarkers400Two = {
  success: boolean
  message: string
}

export type PostApiMarkers400Three = {
  success: boolean
  message: string
}

export type GetApiMarkersById200OneDataDescription = string | null

export type GetApiMarkersById200OneDataAddress = string | null

export type GetApiMarkersById200OneDataImageUrl = string | null

export type GetApiMarkersById200OneDataCreatedAt = unknown | string | string | number

export type GetApiMarkersById200OneDataUpdatedAt = unknown | string | string | number

export type GetApiMarkersById200OneDataUserAvatar = string | null

export type GetApiMarkersById200OneDataUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkersById200OneDataUserAvatar
}

export type GetApiMarkersById200OneData = {
  id: string
  title: string
  description: GetApiMarkersById200OneDataDescription
  latitude: number
  longitude: number
  address: GetApiMarkersById200OneDataAddress
  imageUrl: GetApiMarkersById200OneDataImageUrl
  userId: string
  createdAt: GetApiMarkersById200OneDataCreatedAt
  updatedAt: GetApiMarkersById200OneDataUpdatedAt
  user: GetApiMarkersById200OneDataUser
}

export type GetApiMarkersById200One = {
  success: boolean
  data: GetApiMarkersById200OneData
}

export type GetApiMarkersById200TwoDataDescription = string | null

export type GetApiMarkersById200TwoDataAddress = string | null

export type GetApiMarkersById200TwoDataImageUrl = string | null

export type GetApiMarkersById200TwoDataCreatedAt = unknown | string | string | number

export type GetApiMarkersById200TwoDataUpdatedAt = unknown | string | string | number

export type GetApiMarkersById200TwoDataUserAvatar = string | null

export type GetApiMarkersById200TwoDataUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkersById200TwoDataUserAvatar
}

export type GetApiMarkersById200TwoData = {
  id: string
  title: string
  description: GetApiMarkersById200TwoDataDescription
  latitude: number
  longitude: number
  address: GetApiMarkersById200TwoDataAddress
  imageUrl: GetApiMarkersById200TwoDataImageUrl
  userId: string
  createdAt: GetApiMarkersById200TwoDataCreatedAt
  updatedAt: GetApiMarkersById200TwoDataUpdatedAt
  user: GetApiMarkersById200TwoDataUser
}

export type GetApiMarkersById200Two = {
  success: boolean
  data: GetApiMarkersById200TwoData
}

export type GetApiMarkersById200ThreeDataDescription = string | null

export type GetApiMarkersById200ThreeDataAddress = string | null

export type GetApiMarkersById200ThreeDataImageUrl = string | null

export type GetApiMarkersById200ThreeDataCreatedAt = unknown | string | string | number

export type GetApiMarkersById200ThreeDataUpdatedAt = unknown | string | string | number

export type GetApiMarkersById200ThreeDataUserAvatar = string | null

export type GetApiMarkersById200ThreeDataUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkersById200ThreeDataUserAvatar
}

export type GetApiMarkersById200ThreeData = {
  id: string
  title: string
  description: GetApiMarkersById200ThreeDataDescription
  latitude: number
  longitude: number
  address: GetApiMarkersById200ThreeDataAddress
  imageUrl: GetApiMarkersById200ThreeDataImageUrl
  userId: string
  createdAt: GetApiMarkersById200ThreeDataCreatedAt
  updatedAt: GetApiMarkersById200ThreeDataUpdatedAt
  user: GetApiMarkersById200ThreeDataUser
}

export type GetApiMarkersById200Three = {
  success: boolean
  data: GetApiMarkersById200ThreeData
}

export type GetApiMarkersById404One = {
  success: boolean
  message: string
}

export type GetApiMarkersById404Two = {
  success: boolean
  message: string
}

export type GetApiMarkersById404Three = {
  success: boolean
  message: string
}

export type PutApiMarkersByIdBodyOne = {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string
  /** @maxLength 1000 */
  description?: string
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude?: number
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude?: number
  /** @maxLength 500 */
  address?: string
  imageUrl?: string
}

export type PutApiMarkersByIdBodyTwo = {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string
  /** @maxLength 1000 */
  description?: string
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude?: number
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude?: number
  /** @maxLength 500 */
  address?: string
  imageUrl?: string
}

export type PutApiMarkersByIdBodyThree = {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string
  /** @maxLength 1000 */
  description?: string
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude?: number
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude?: number
  /** @maxLength 500 */
  address?: string
  imageUrl?: string
}

export type PutApiMarkersById200OneDataDescription = string | null

export type PutApiMarkersById200OneDataAddress = string | null

export type PutApiMarkersById200OneDataImageUrl = string | null

export type PutApiMarkersById200OneDataCreatedAt = unknown | string | string | number

export type PutApiMarkersById200OneDataUpdatedAt = unknown | string | string | number

export type PutApiMarkersById200OneDataUserAvatar = string | null

export type PutApiMarkersById200OneDataUser = {
  id: string
  name: string
  email: string
  avatar: PutApiMarkersById200OneDataUserAvatar
}

export type PutApiMarkersById200OneData = {
  id: string
  title: string
  description: PutApiMarkersById200OneDataDescription
  latitude: number
  longitude: number
  address: PutApiMarkersById200OneDataAddress
  imageUrl: PutApiMarkersById200OneDataImageUrl
  userId: string
  createdAt: PutApiMarkersById200OneDataCreatedAt
  updatedAt: PutApiMarkersById200OneDataUpdatedAt
  user: PutApiMarkersById200OneDataUser
}

export type PutApiMarkersById200One = {
  success: boolean
  data: PutApiMarkersById200OneData
}

export type PutApiMarkersById200TwoDataDescription = string | null

export type PutApiMarkersById200TwoDataAddress = string | null

export type PutApiMarkersById200TwoDataImageUrl = string | null

export type PutApiMarkersById200TwoDataCreatedAt = unknown | string | string | number

export type PutApiMarkersById200TwoDataUpdatedAt = unknown | string | string | number

export type PutApiMarkersById200TwoDataUserAvatar = string | null

export type PutApiMarkersById200TwoDataUser = {
  id: string
  name: string
  email: string
  avatar: PutApiMarkersById200TwoDataUserAvatar
}

export type PutApiMarkersById200TwoData = {
  id: string
  title: string
  description: PutApiMarkersById200TwoDataDescription
  latitude: number
  longitude: number
  address: PutApiMarkersById200TwoDataAddress
  imageUrl: PutApiMarkersById200TwoDataImageUrl
  userId: string
  createdAt: PutApiMarkersById200TwoDataCreatedAt
  updatedAt: PutApiMarkersById200TwoDataUpdatedAt
  user: PutApiMarkersById200TwoDataUser
}

export type PutApiMarkersById200Two = {
  success: boolean
  data: PutApiMarkersById200TwoData
}

export type PutApiMarkersById200ThreeDataDescription = string | null

export type PutApiMarkersById200ThreeDataAddress = string | null

export type PutApiMarkersById200ThreeDataImageUrl = string | null

export type PutApiMarkersById200ThreeDataCreatedAt = unknown | string | string | number

export type PutApiMarkersById200ThreeDataUpdatedAt = unknown | string | string | number

export type PutApiMarkersById200ThreeDataUserAvatar = string | null

export type PutApiMarkersById200ThreeDataUser = {
  id: string
  name: string
  email: string
  avatar: PutApiMarkersById200ThreeDataUserAvatar
}

export type PutApiMarkersById200ThreeData = {
  id: string
  title: string
  description: PutApiMarkersById200ThreeDataDescription
  latitude: number
  longitude: number
  address: PutApiMarkersById200ThreeDataAddress
  imageUrl: PutApiMarkersById200ThreeDataImageUrl
  userId: string
  createdAt: PutApiMarkersById200ThreeDataCreatedAt
  updatedAt: PutApiMarkersById200ThreeDataUpdatedAt
  user: PutApiMarkersById200ThreeDataUser
}

export type PutApiMarkersById200Three = {
  success: boolean
  data: PutApiMarkersById200ThreeData
}

export type PutApiMarkersById403One = {
  success: boolean
  message: string
}

export type PutApiMarkersById403Two = {
  success: boolean
  message: string
}

export type PutApiMarkersById403Three = {
  success: boolean
  message: string
}

export type PutApiMarkersById404One = {
  success: boolean
  message: string
}

export type PutApiMarkersById404Two = {
  success: boolean
  message: string
}

export type PutApiMarkersById404Three = {
  success: boolean
  message: string
}

export type DeleteApiMarkersById200One = {
  success: boolean
  message: string
}

export type DeleteApiMarkersById200Two = {
  success: boolean
  message: string
}

export type DeleteApiMarkersById200Three = {
  success: boolean
  message: string
}

export type DeleteApiMarkersById403One = {
  success: boolean
  message: string
}

export type DeleteApiMarkersById403Two = {
  success: boolean
  message: string
}

export type DeleteApiMarkersById403Three = {
  success: boolean
  message: string
}

export type DeleteApiMarkersById404One = {
  success: boolean
  message: string
}

export type DeleteApiMarkersById404Two = {
  success: boolean
  message: string
}

export type DeleteApiMarkersById404Three = {
  success: boolean
  message: string
}

export type GetApiMarkersMyMarkers200OneDataItemDescription = string | null

export type GetApiMarkersMyMarkers200OneDataItemAddress = string | null

export type GetApiMarkersMyMarkers200OneDataItemImageUrl = string | null

export type GetApiMarkersMyMarkers200OneDataItemCreatedAt = unknown | string | string | number

export type GetApiMarkersMyMarkers200OneDataItemUpdatedAt = unknown | string | string | number

export type GetApiMarkersMyMarkers200OneDataItemUserAvatar = string | null

export type GetApiMarkersMyMarkers200OneDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkersMyMarkers200OneDataItemUserAvatar
}

export type GetApiMarkersMyMarkers200OneDataItem = {
  id: string
  title: string
  description: GetApiMarkersMyMarkers200OneDataItemDescription
  latitude: number
  longitude: number
  address: GetApiMarkersMyMarkers200OneDataItemAddress
  imageUrl: GetApiMarkersMyMarkers200OneDataItemImageUrl
  userId: string
  createdAt: GetApiMarkersMyMarkers200OneDataItemCreatedAt
  updatedAt: GetApiMarkersMyMarkers200OneDataItemUpdatedAt
  user: GetApiMarkersMyMarkers200OneDataItemUser
}

export type GetApiMarkersMyMarkers200One = {
  success: boolean
  data: GetApiMarkersMyMarkers200OneDataItem[]
}

export type GetApiMarkersMyMarkers200TwoDataItemDescription = string | null

export type GetApiMarkersMyMarkers200TwoDataItemAddress = string | null

export type GetApiMarkersMyMarkers200TwoDataItemImageUrl = string | null

export type GetApiMarkersMyMarkers200TwoDataItemCreatedAt = unknown | string | string | number

export type GetApiMarkersMyMarkers200TwoDataItemUpdatedAt = unknown | string | string | number

export type GetApiMarkersMyMarkers200TwoDataItemUserAvatar = string | null

export type GetApiMarkersMyMarkers200TwoDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkersMyMarkers200TwoDataItemUserAvatar
}

export type GetApiMarkersMyMarkers200TwoDataItem = {
  id: string
  title: string
  description: GetApiMarkersMyMarkers200TwoDataItemDescription
  latitude: number
  longitude: number
  address: GetApiMarkersMyMarkers200TwoDataItemAddress
  imageUrl: GetApiMarkersMyMarkers200TwoDataItemImageUrl
  userId: string
  createdAt: GetApiMarkersMyMarkers200TwoDataItemCreatedAt
  updatedAt: GetApiMarkersMyMarkers200TwoDataItemUpdatedAt
  user: GetApiMarkersMyMarkers200TwoDataItemUser
}

export type GetApiMarkersMyMarkers200Two = {
  success: boolean
  data: GetApiMarkersMyMarkers200TwoDataItem[]
}

export type GetApiMarkersMyMarkers200ThreeDataItemDescription = string | null

export type GetApiMarkersMyMarkers200ThreeDataItemAddress = string | null

export type GetApiMarkersMyMarkers200ThreeDataItemImageUrl = string | null

export type GetApiMarkersMyMarkers200ThreeDataItemCreatedAt = unknown | string | string | number

export type GetApiMarkersMyMarkers200ThreeDataItemUpdatedAt = unknown | string | string | number

export type GetApiMarkersMyMarkers200ThreeDataItemUserAvatar = string | null

export type GetApiMarkersMyMarkers200ThreeDataItemUser = {
  id: string
  name: string
  email: string
  avatar: GetApiMarkersMyMarkers200ThreeDataItemUserAvatar
}

export type GetApiMarkersMyMarkers200ThreeDataItem = {
  id: string
  title: string
  description: GetApiMarkersMyMarkers200ThreeDataItemDescription
  latitude: number
  longitude: number
  address: GetApiMarkersMyMarkers200ThreeDataItemAddress
  imageUrl: GetApiMarkersMyMarkers200ThreeDataItemImageUrl
  userId: string
  createdAt: GetApiMarkersMyMarkers200ThreeDataItemCreatedAt
  updatedAt: GetApiMarkersMyMarkers200ThreeDataItemUpdatedAt
  user: GetApiMarkersMyMarkers200ThreeDataItemUser
}

export type GetApiMarkersMyMarkers200Three = {
  success: boolean
  data: GetApiMarkersMyMarkers200ThreeDataItem[]
}

export const getElysiaDocumentation = () => {
  const postApiAuthRegister = (
    postApiAuthRegisterBody:
      | PostApiAuthRegisterBodyOne
      | PostApiAuthRegisterBodyTwo
      | PostApiAuthRegisterBodyThree,
  ) => {
    return apiMutator<PostApiAuthRegister201One | Blob | PostApiAuthRegister201Three>({
      url: `/api/auth/register`,
      method: 'POST',
      data: postApiAuthRegisterBody,
    })
  }

  const postApiAuthLogin = (
    postApiAuthLoginBody:
      | PostApiAuthLoginBodyOne
      | PostApiAuthLoginBodyTwo
      | PostApiAuthLoginBodyThree,
  ) => {
    return apiMutator<PostApiAuthLogin200One | Blob | PostApiAuthLogin200Three>({
      url: `/api/auth/login`,
      method: 'POST',
      data: postApiAuthLoginBody,
    })
  }

  const postApiAuthLogout = () => {
    return apiMutator<PostApiAuthLogout200One | Blob | PostApiAuthLogout200Three>({
      url: `/api/auth/logout`,
      method: 'POST',
    })
  }

  const getApiAuthMe = () => {
    return apiMutator<GetApiAuthMe200One | Blob | GetApiAuthMe200Three>({
      url: `/api/auth/me`,
      method: 'GET',
    })
  }

  const getApiUsers = (params?: GetApiUsersParams) => {
    return apiMutator<GetApiUsers200One | Blob | GetApiUsers200Three>({
      url: `/api/users/`,
      method: 'GET',
      params,
    })
  }

  const getApiUsersById = (id: string) => {
    return apiMutator<GetApiUsersById200One | Blob | GetApiUsersById200Three>({
      url: `/api/users/${id}`,
      method: 'GET',
    })
  }

  const getApiUsersByIdMarkers = (id: string, params?: GetApiUsersByIdMarkersParams) => {
    return apiMutator<GetApiUsersByIdMarkers200One | Blob | GetApiUsersByIdMarkers200Three>({
      url: `/api/users/${id}/markers`,
      method: 'GET',
      params,
    })
  }

  const putApiUsersProfile = (
    putApiUsersProfileBody:
      | PutApiUsersProfileBodyOne
      | PutApiUsersProfileBodyTwo
      | PutApiUsersProfileBodyThree,
  ) => {
    return apiMutator<PutApiUsersProfile200One | Blob | PutApiUsersProfile200Three>({
      url: `/api/users/profile`,
      method: 'PUT',
      data: putApiUsersProfileBody,
    })
  }

  const putApiUsersPassword = (
    putApiUsersPasswordBody:
      | PutApiUsersPasswordBodyOne
      | PutApiUsersPasswordBodyTwo
      | PutApiUsersPasswordBodyThree,
  ) => {
    return apiMutator<PutApiUsersPassword200One | Blob | PutApiUsersPassword200Three>({
      url: `/api/users/password`,
      method: 'PUT',
      data: putApiUsersPasswordBody,
    })
  }

  const deleteApiUsersAccount = () => {
    return apiMutator<DeleteApiUsersAccount200One | Blob | DeleteApiUsersAccount200Three>({
      url: `/api/users/account`,
      method: 'DELETE',
    })
  }

  const getApiMarkers = () => {
    return apiMutator<GetApiMarkers200One | Blob | GetApiMarkers200Three>({
      url: `/api/markers/`,
      method: 'GET',
    })
  }

  const postApiMarkers = (
    postApiMarkersBody: PostApiMarkersBodyOne | PostApiMarkersBodyTwo | PostApiMarkersBodyThree,
  ) => {
    return apiMutator<PostApiMarkers201One | Blob | PostApiMarkers201Three>({
      url: `/api/markers/`,
      method: 'POST',
      data: postApiMarkersBody,
    })
  }

  const getApiMarkersById = (id: string) => {
    return apiMutator<GetApiMarkersById200One | Blob | GetApiMarkersById200Three>({
      url: `/api/markers/${id}`,
      method: 'GET',
    })
  }

  const putApiMarkersById = (
    id: string,
    putApiMarkersByIdBody:
      | PutApiMarkersByIdBodyOne
      | PutApiMarkersByIdBodyTwo
      | PutApiMarkersByIdBodyThree,
  ) => {
    return apiMutator<PutApiMarkersById200One | Blob | PutApiMarkersById200Three>({
      url: `/api/markers/${id}`,
      method: 'PUT',
      data: putApiMarkersByIdBody,
    })
  }

  const deleteApiMarkersById = (id: string) => {
    return apiMutator<DeleteApiMarkersById200One | Blob | DeleteApiMarkersById200Three>({
      url: `/api/markers/${id}`,
      method: 'DELETE',
    })
  }

  const getApiMarkersMyMarkers = () => {
    return apiMutator<GetApiMarkersMyMarkers200One | Blob | GetApiMarkersMyMarkers200Three>({
      url: `/api/markers/my/markers`,
      method: 'GET',
    })
  }

  return {
    postApiAuthRegister,
    postApiAuthLogin,
    postApiAuthLogout,
    getApiAuthMe,
    getApiUsers,
    getApiUsersById,
    getApiUsersByIdMarkers,
    putApiUsersProfile,
    putApiUsersPassword,
    deleteApiUsersAccount,
    getApiMarkers,
    postApiMarkers,
    getApiMarkersById,
    putApiMarkersById,
    deleteApiMarkersById,
    getApiMarkersMyMarkers,
  }
}
export type PostApiAuthRegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['postApiAuthRegister']>>
>
export type PostApiAuthLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['postApiAuthLogin']>>
>
export type PostApiAuthLogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['postApiAuthLogout']>>
>
export type GetApiAuthMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiAuthMe']>>
>
export type GetApiUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiUsers']>>
>
export type GetApiUsersByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiUsersById']>>
>
export type GetApiUsersByIdMarkersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiUsersByIdMarkers']>>
>
export type PutApiUsersProfileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['putApiUsersProfile']>>
>
export type PutApiUsersPasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['putApiUsersPassword']>>
>
export type DeleteApiUsersAccountResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['deleteApiUsersAccount']>>
>
export type GetApiMarkersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiMarkers']>>
>
export type PostApiMarkersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['postApiMarkers']>>
>
export type GetApiMarkersByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiMarkersById']>>
>
export type PutApiMarkersByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['putApiMarkersById']>>
>
export type DeleteApiMarkersByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['deleteApiMarkersById']>>
>
export type GetApiMarkersMyMarkersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getElysiaDocumentation>['getApiMarkersMyMarkers']>>
>
